In [1]:
import numpy as np

In [3]:
n1 = np.array([1,2,3])
n1.ndim

1

In [5]:
n2 = np.array([[1,2,3],[4,5,6]])
n2.ndim

2

In [6]:
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
n2[1,0]

np.int64(4)

In [8]:
n2[1,2] = 7

In [9]:
n2

array([[1, 2, 3],
       [4, 5, 7]])

In [11]:
n2.dtype

dtype('int64')

In [12]:
n2.itemsize

8

In [13]:
n2.size

6

In [14]:
n2.shape

(2, 3)

In [15]:
np.sort(n2)

array([[1, 2, 3],
       [4, 5, 7]])

In [17]:
np.sort(n2,axis=None)

array([1, 2, 3, 4, 5, 7])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])