In [1]:
import numpy as np

In [3]:
n1 = np.array([1,2,3])
n1.ndim

1

In [5]:
n2 = np.array([[1,2,3],[4,5,6]])
n2.ndim

2

In [6]:
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
n2[1,0]

np.int64(4)

In [8]:
n2[1,2] = 7

In [9]:
n2

array([[1, 2, 3],
       [4, 5, 7]])

In [11]:
n2.dtype

dtype('int64')

In [12]:
n2.itemsize

8

In [13]:
n2.size

6

In [14]:
n2.shape

(2, 3)

In [15]:
np.sort(n2)

array([[1, 2, 3],
       [4, 5, 7]])

In [17]:
np.sort(n2,axis=None)

array([1, 2, 3, 4, 5, 7])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.arange(50,70)

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

In [22]:
np.arange(50,70,2)

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68])

In [23]:
np.linspace(50,70)

array([50.        , 50.40816327, 50.81632653, 51.2244898 , 51.63265306,
       52.04081633, 52.44897959, 52.85714286, 53.26530612, 53.67346939,
       54.08163265, 54.48979592, 54.89795918, 55.30612245, 55.71428571,
       56.12244898, 56.53061224, 56.93877551, 57.34693878, 57.75510204,
       58.16326531, 58.57142857, 58.97959184, 59.3877551 , 59.79591837,
       60.20408163, 60.6122449 , 61.02040816, 61.42857143, 61.83673469,
       62.24489796, 62.65306122, 63.06122449, 63.46938776, 63.87755102,
       64.28571429, 64.69387755, 65.10204082, 65.51020408, 65.91836735,
       66.32653061, 66.73469388, 67.14285714, 67.55102041, 67.95918367,
       68.36734694, 68.7755102 , 69.18367347, 69.59183673, 70.        ])

In [24]:
np.linspace(50,70,5)

array([50., 55., 60., 65., 70.])

In [25]:
n2

array([[1, 2, 3],
       [4, 5, 7]])

In [26]:
n2.flatten()

array([1, 2, 3, 4, 5, 7])

In [27]:
n2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 7]])

In [28]:
n2.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [7]])

In [29]:
n2.min()

np.int64(1)

In [30]:
n2.max()

np.int64(7)

In [31]:
n2.std()

np.float64(1.9720265943665387)

In [32]:
n2.sum()

np.int64(22)

In [33]:
n2.sum(axis=0)

array([ 5,  7, 10])

In [34]:
n2

array([[1, 2, 3],
       [4, 5, 7]])

In [35]:
n2.sum(axis=1)

array([ 6, 16])

In [37]:
np.sqrt(n2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.64575131]])

In [39]:
np.square(n2)

array([[ 1,  4,  9],
       [16, 25, 49]])

In [40]:
np.std(n2)

np.float64(1.9720265943665387)