In [1]:
import numpy as np

In [2]:
n1 = np.array([
    [100,200,300],
    [400,500,600],
    [700,800,900]
])
n2 = np.array([
    [150,250,350],
    [450,550,650],
    [750,850,950]
])

In [3]:
n1 + n2

array([[ 250,  450,  650],
       [ 850, 1050, 1250],
       [1450, 1650, 1850]])

In [4]:
n2 - n1

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [5]:
(n2-n1)*100/n1

array([[50.        , 25.        , 16.66666667],
       [12.5       , 10.        ,  8.33333333],
       [ 7.14285714,  6.25      ,  5.55555556]])

In [6]:
n1 * n2

array([[ 15000,  50000, 105000],
       [180000, 275000, 390000],
       [525000, 680000, 855000]])

In [7]:
np.sum(n2)

np.int64(4950)

In [8]:
n5 = np.array([
    [100,2],
    [300,4]
])

n6 = np.array([10,100])

np.dot(n5,n6)

array([1200, 3400])

In [10]:
n7 = np.array([2,4])
n8 = np.array([6,8])
np.cross(n7,n8)

C:\Users\mailt\AppData\Local\Temp\ipykernel_19024\4107387280.py:3: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(n7,n8)


array(-8)