In [1]:
import numpy as np

In [3]:
numpy_array = np.arange(100)
numpy_array[:5]

array([0, 1, 2, 3, 4])

In [4]:
numpy_array.nbytes

800

In [7]:
l1 = [1,2,3]
l2 = [4,5,6]
tuple(zip(l1,l2))
l3 = [x+y for x,y in zip(l1,l2)]
print(l3)

[5, 7, 9]


In [10]:
n1 = np.arange(5)
n2 = np.arange(5)
n3 = n1+n2
print(n3)

[0 2 4 6 8]


In [11]:
n1-n2

array([0, 0, 0, 0, 0])

In [12]:
n1*n2

array([ 0,  1,  4,  9, 16])