In [1]:
import numpy as np

In [2]:
a= np.array([1,2,3,4])

In [3]:
a[0:2]

array([1, 2])

In [4]:
a[2:]

array([3, 4])

In [5]:
a[-1]

np.int64(4)

In [6]:
a[-2:]

array([3, 4])

In [7]:
b=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [8]:
b[1,2]

np.int64(6)

In [9]:
b[2,0]

np.int64(7)

In [10]:
b[-1]

array([7, 8, 9])

In [11]:
b[-1,0:2]

array([7, 8])

In [12]:
b[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])